name: Cloud Security IaC Scan
on:
  workflow_call:
    inputs:
      project_key:
        required: true
        type: string
      path:
        required: true
        type: string
jobs:
  IaC-Scan:
    name: IaC Scan - Orca
    runs-on: ubuntu-latest
    steps:
      # Checkout tempus-2 repo
      - name: Checkout tempus-2 Repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
          
      # Checkout tempus-1 repo
      - name: Checkout tempus-1 Repository
        uses: actions/checkout@v5
        with:
          repository: rahg0/tempus-1
          ref: main
          path: tempus-1

      # Vendor-recommended diagnostic step
      - name: Listing files
        run: |
          echo "Listing all the files...."
          ls -lah
          
          echo "Listing tempus-1/.github directory..."
          ls -lah tempus-1/.github/
          echo "Listing tempus-1/.github/workflows directory..."
          ls -lah tempus-1/.github/workflows/
          echo "Listing production-custom-queries directory..."
          ls -lah tempus-1/.github/workflows/non-production-custom-queries/
          echo "Listing gcp-owner-role directory..."
          ls -lah tempus-1/.github/workflows/non-production-custom-queries/gcp-owner-role


          echo "Listing .github directory..."
          ls -lah .github/
          echo "Listing .github/workflows directory..."
          ls -lah .github/workflows/

          
      - name: Run Orca IaC Scan
        uses: orcasecurity/shiftleft-iac-action@v1
        id: orca_scan
        with:
          api_token: ${{ secrets.ORCA_SECURITY_API_TOKEN_REPO }}
          project_key: ${{ inputs.project_key }}
          path: ${{ inputs.path }}
          format: "cli,sarif"
          output: "results/"
          custom_controls: "tempus-1/.github/workflows/non-production-custom-queries/gcp-owner-role"
